### ISSUE TITLE
Adding Wien2k k-points

### ISSUE THREAD

**Issue by subhasishmandal** [usnistgov/jarvis#117]
There is some problem with our existing code to generate wien2k k-path given a cif file, namely it gives some weird lines in the band plot. No problem in running  and getting the energy eignevalues.  This is due to sudden jump in the k-path that happens for certain lattice vectors. Simple cubics are fine.

**Comment by knc6** [comment]
Hi @subhasishmandal 

I have added the Wien2K kpoint generator in jarvis.io.wien2k.inputs module now. You can use as follows:

from jarvis.core.atoms import Atoms
from jarvis.io.wien2k.inputs import get_wien_kpoints
atoms=Atoms.from_cif('path_to_your.cif')
data = get_wien_kpoints(atoms=s, write_file=True, filename='case.kpoints')


The bandstructure plotter for wien2K is available now in jarvis.io.wien2k.outputs. https://github.com/usnistgov/jarvis/blob/master/jarvis/io/wien2k/outputs.py
