### ISSUE TITLE
LICENSE file is messed up

### ISSUE THREAD

**Issue by wd15** [usnistgov/jarvis#127]
This is messed up:

https://github.com/usnistgov/jarvis/blob/master/LICENSE

Let's change it to 

https://github.com/usnistgov/fipy/blob/master/LICENSE.rst

but with no `.rst`. This is exactly the same as the official license

https://www.nist.gov/open/copyright-fair-use-and-licensing-statements-srd-data-software-and-technical-series-publications

**Comment by knc6** [comment]
@wd15 
See https://github.com/usnistgov/jarvis/blob/master/LICENSE.rst

**Comment by wd15** [comment]
It doesn't need to have the `.rst`. That indicates that it's restructured text. Just `LICENSE` is fine I think.
