### ISSUE TITLE
Don't pin versions in setup.py

### ISSUE THREAD

**Issue by wd15** [usnistgov/jarvis#13]
Apparently, it's not good pracitce to pin versions in setup.py, see https://packaging.python.org/discussions/install-requires-vs-requirements/. 

> It is not considered best practice to use install_requires to pin dependencies to specific versions, or to specify sub-dependencies (i.e. dependencies of your dependencies). This is overly-restrictive, and prevents the user from gaining the benefit of dependency upgrades.

**Comment by knc6** [comment]
All pinned versions removed
