### ISSUE TITLE
Release versioning and tagging

### ISSUE THREAD

**Issue by orbsmiv** [usnistgov/jarvis#16]
I'm currently implementing an automatic build of JARVIS for our HPC, using the Easybuild tool. I'm having some difficulty with Jarvis due to the variable version formatting and also the inconsistency between the GitHub versioning/tagging and the version specified inside _setup.py_. Can I request that this is standardised going forwards, e.g. using vYYYY.MM.DD (`v2018.11.06` in the case of the most recent release)?

**Comment by knc6** [comment]
Good suggestion, just fixed the version in YYYY.MM.DD format

**Comment by wd15** [comment]
@knc6, I think you need to retag the commits, https://github.com/usnistgov/jarvis/releases

For example v10.23.2018 still has the wrong tag, 10.23.2018.
