### ISSUE TITLE
Running the tests modifies a whole bunch of json files

### ISSUE THREAD

**Issue by wd15** [usnistgov/jarvis#20]
Running the tests modifies a bunch of json files and leaves the repository in a modified state. Tests should never modify the contents of the repository. Tests should write all data to `/tmp` and then delete any files that are written.

After running 

    $ py.tests

the repo is left with

    $ git status
    On branch master
    Changes not staged for commit:
      (use "git add <file>..." to update what will be committed)
      (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   jarvis/vasp/examples/SiOptb88/ENCUTbulk@mp_149-500.json
        modified:   jarvis/vasp/examples/SiOptb88/ENCUTbulk@mp_149-600.json
	    modified:   jarvis/vasp/examples/SiOptb88/ENCUTbulk@mp_149-650.json
	    modified:   jarvis/vasp/examples/SiOptb88/ENCUTbulk@mp_149-700.json
    ...

Do these json files need to be stored if they can be generated quickly?

Edit: also a weird directory is created `jarvis/tests/tmp/`. Tests should not create any directories in the repository either. Use `/tmp` or whatever the system directory is for the OS. Python has OS independent ways to write to temporary storage which work across multiple platforms.

**Comment by knc6** [comment]
Should be fixed in the current version
