### ISSUE TITLE
Line 10: from fractions import gcd (removed in Python 3.9)

### ISSUE THREAD

**Issue by pranoy-ray** [usnistgov/jarvis#206]
"from fractions import gcd" has been removed in Python 3.9

Possible Solution: math.gcd() is now used in place of it.

Find more information on this error here: [https://stackoverflow.com/questions/66174862/import-error-cant-import-name-gcd-from-fractions](https://stackoverflow.com/questions/66174862/import-error-cant-import-name-gcd-from-fractions)

I have included an image of the error thrown below:
![Screen Shot 2021-11-23 at 12 03 40 AM](https://user-images.githubusercontent.com/80657118/142973856-70eeb9b5-a467-4620-b21b-f27febcc310a.png)

**Comment by knc6** [comment]
Fixed in the latest version: 2021.12.16
