### ISSUE TITLE
Implement test coverage 

### ISSUE THREAD

**Issue by wd15** [usnistgov/jarvis#23]
Example on Travis CI: https://travis-ci.org/materialsinnovation/pymks/jobs/408609998#L1395

Example configuration: https://github.com/materialsinnovation/pymks/blob/develop/setup.cfg#L6

**Comment by knc6** [comment]
Implemented test coverage, example: https://codecov.io/gh/knc6/jarvis/commit/bc7cac7cc3afbcfcedb57c6f1f3b10538443383f
