### ISSUE TITLE
Cannot parse selective dynamics POSCAR

### ISSUE THREAD

**Issue by sthartman** [usnistgov/jarvis#242]
**Describe the bug**
Hello,
The vasp POSCAR parser cannot handle the selective dynamics flag, because the parser assumes that the atoms will be listed beginning on line index 8. However, the selective dynamics flag shows up as an optional line on index seven, pushing 'direct' or 'cartesian' to line index 8.
The simplest fix would probably be to check if line index 7 begins with 'S' or 's', and if it does, do the appropriate logic and then pull that element out of the list so the rest of the parser doesn't have to be changed.

**Comment by knc6** [comment]
Thanks @sthartman for reporting the bug. 
It should be fixed in the [current version](https://github.com/usnistgov/jarvis/blob/master/jarvis/io/vasp/inputs.py#L181):
