### ISSUE TITLE
Delete plt.switch_backend("agg") in jarvis/jarvis/db/figshare.py

### ISSUE THREAD

**Issue by nahaharo** [usnistgov/jarvis#269]
I don't know where does this come from but this changes matplotlib backend without notice.

This code changes the behavier of matplotlib.

In my case, figure was not properly showed when I import jarvis.db.figshare.

I think this code is appeared when developing.

Please delete this.

**Comment by knc6** [comment]
Good catch, fixed in the current version
https://github.com/usnistgov/jarvis/blob/master/jarvis/db/figshare.py#L23
