### ISSUE TITLE
Move website to pages.nist.gov

### ISSUE THREAD

**Issue by wd15** [usnistgov/jarvis#9]
Using pages.nist.gov would allow the site to use templates without requiring a backend app. Jekyll is very good for processing smalll/medium volume static data, which is currently an issue for the jarvis web site.

**Comment by knc6** [comment]
https://pages.nist.gov/jarvis/

**Comment by knc6** [comment]
https://github.com/usnistgov/pages-root/wiki/Adding-NIST-required-branding-and-features-to-your-site
https://github.com/usnistgov/pages-root/wiki/Configuring-your-repo-for-publishing-on-pages.nist.gov

**Comment by wd15** [comment]
That's a start!! I'm thinking that it would be easier to host your site with pages as everything is in JSON files. It all deploys straight from Github instead of dealing with CTCMS.

**Comment by knc6** [comment]
We are migrating everything from CTCMS and Flask to MDCS/CDCS Django apps (https://jarvis.nist.gov/) now.

I am making docs with MkDocs (https://jarvis-materials-design.github.io/dbdocs/tutorials/) and would hopefully host on pages.nist.gov/jarvis. Have you used MkDocs for pages.nist.gov or do you know if someone in our group does?

**Comment by wd15** [comment]
> We are migrating everything from CTCMS and Flask to MDCS/CDCS Django apps (https://jarvis.nist.gov/) now.

Awesome. Good luck with it.

> I am making docs with MkDocs (https://jarvis-materials-design.github.io/dbdocs/tutorials/) and would hopefully host on pages.nist.gov/jarvis. Have you used MkDocs for pages.nist.gov or do you know if someone in our group does?

No sorry, never used it.

**Comment by knc6** [comment]
A version is here:https://pages.nist.gov/jarvis/, need to fix the styling.
but I prefer  https://jarvis-materials-design.github.io/dbdocs/tutorials/
